name: Deploy to Server

on:
  push:
    branches:
      - master
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key Manually
        env:
          SSH_PRIVATE_KEY: ${{ secrets.UBUNTU_SERVER }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.UBUNTU_SERVER }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 139.177.197.79 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to Server
        env:
          GITHUB_REF: ${{ github.ref }}
        run: |
          ssh -o StrictHostKeyChecking=no gituser@139.177.197.79 'bash -s' << 'EOF'
          # Debugging the branch name extraction
          echo "GITHUB_REF: $GITHUB_REF"
          BRANCH_NAME=$(echo $GITHUB_REF | sed 's|refs/heads/||')
          echo "Extracted BRANCH_NAME: $BRANCH_NAME"

          if [ "$BRANCH_NAME" = "master" ]; then
            DEPLOY_DIR="/var/www/html/portfolio/prod"
          elif [ "$BRANCH_NAME" = "staging" ]; then
            DEPLOY_DIR="/var/www/html/portfolio/staging"
          else
            echo "Branch name $BRANCH_NAME is not configured for deployment"
            exit 1
          fi

          echo "Deploying to $DEPLOY_DIR"
          cd $DEPLOY_DIR
          if [ $? -eq 0 ]; then
            echo "Directory exists, listing contents:"
            ls -la
            echo "Stashing any local changes..."
            git stash push --include-untracked
            echo "Pulling latest changes from origin/$BRANCH_NAME..."
            git pull origin $BRANCH_NAME
          else
            echo "Directory $DEPLOY_DIR does not exist"
            exit 1
          fi
          EOF
